#!/usr/bin/env bash

set -ex

# Create an array of block devices, excluding cdroms and loopbacks
mapfile -t DEVICES < <(lsblk -pindo NAME -e 7,11)

# Create a boot partition on the 0th and make LVM PVs out of the remainder
for i in ${!DEVICES[@]} ; do
  sgdisk --zap-all ${DEVICES[$i]}
  sgdisk -n 0:0:+1GiB -t 0:ef00 -c 0:boot${i} ${DEVICES[$i]}
  sgdisk -n 0:0:0 -t 0:8e00 -c 0:pv${i} ${DEVICES[$i]}
done

sleep 5
mdadm -C /dev/md0 -l1 -n2 -N array0 --metadata 1.0 /dev/disk/by-partlabel/boot*
sgdisk -n 0:0:0 -t 0:ef00 -c 0:boot /dev/md0

# Create LVM PVs
for device in /dev/disk/by-partlabel/pv* ; do
  pvcreate ${device}
done

# Create LVM VGs
vgcreate vg0 /dev/disk/by-partlabel/pv*

# Create LVM LVs
lvcreate vg0 -L 2G -n root --type raid0
lvcreate vg0 -L 1G -n var --type raid0
lvcreate vg0 -L 1G -n swap --type raid0

# Format everything
mkfs.fat -F32 -n boot /dev/md0p1
mkswap -L swap /dev/vg0/swap
mkfs.ext4 -L root /dev/vg0/root
mkfs.ext4 -L var /dev/vg0/var

# Mount everything
mkdir -p /mnt/
mount /dev/disk/by-label/root /mnt
mkdir -p /mnt/var
mount /dev/disk/by-label/var /mnt/var

mkdir -p /mnt/boot
mount /dev/disk/by-label/boot /mnt/boot

swapon /dev/vg0/swap

# Install all the files
pacstrap /mnt base linux linux-firmware lvm2 mdadm intel-ucode wpa_supplicant vi bash-completion

# Generate storage configuration
genfstab -U /mnt >> /mnt/etc/fstab

# the following must be indented by tabs, not spaces
arch-chroot /mnt bash <<- EOD
	set -ex
	# Set time
	#ln -sf /usr/share/zoneinfo/Region/City /etc/localtime
	hwclock --systohc
	
	# Set localization
	sed -i 's/^#.*\(en_US.UTF-8\)/\1/' /etc/locale.gen
	locale-gen
	cat > /etc/locale.conf <<< LANG=en_US.UTF-8
	
	# Set console font
	cat > /etc/vconsole.conf <<< FONT=latarcyrheb-sun32

	# the following must be indented by tabs, not spaces
	cat > /etc/hosts <<- EOF
		127.0.0.1	localhost
		::1	localhost
		#127.0.1.1 localhost.localdomain localhost
	EOF
	
	# Add initcpio support for storage
	sed -i '/^HOOKS=/{ s/udev/systemd/; s/block/& mdadm_udev sd-lvm2/; }' /etc/mkinitcpio.conf
	sed -i '/^MODULES=/{ s/(/&dm-raid raid0 raid1/; }' /etc/mkinitcpio.conf
	mkinitcpio -P
	
	# Install boot loader
	bootctl install
	# the following must be indented by tabs, not spaces
	cat > /boot/loader/loader.conf <<- EOF
		default arch
		timeout	4
		console-mode	max
	EOF
	# the following must be indented by tabs, not spaces
	cat > /boot/loader/entries/arch.conf <<- EOF
		title	Arch Linux
		linux	/vmlinuz-linux
		initrd /intel-ucode.img
		initrd /initramfs-linux.img
		options root=LABEL=root rw
	EOF
EOD

reboot
