#!/usr/bin/env bash

set -ex

# Create an array of block devices, excluding cdroms and loopbacks
mapfile -t DEVICES < <(lsblk -pindo NAME -e 7,11)

# Create a boot partition on the 0th and make RAID devices out of the remainder
for i in ${!DEVICES[@]} ; do
  sgdisk --zap-all ${DEVICES[$i]}
  [ ${i} == 0 ] && sgdisk -n 0:0:+1GiB -t 0:ef00 -c 0:boot ${DEVICES[$i]}
  sgdisk -n 0:0:0 -t 0:fd00 -c 0:dev${i} ${DEVICES[$i]}
done

# Set up RAID across devices
modprobe raid0
echo 2 > /sys/module/raid0/parameters/default_layout
for device in /dev/disk/by-partlabel/dev* ; do
  mdadm --misc --zero-superblock ${device}
done
mdadm -C /dev/md0 -l0 -n2 -N array0 /dev/disk/by-partlabel/dev*

# Create LVM PVs
pvcreate /dev/md0

# Create LVM VGs
vgcreate vg0 /dev/md0

# Create LVM LVs
lvcreate vg0 -L 2G -n root
lvcreate vg0 -L 1G -n var
lvcreate vg0 -L 1G -n swap

# Format everything
mkfs.fat -F32 -n boot /dev/disk/by-partlabel/boot
mkswap -L swap /dev/vg0/swap
mkfs.ext4 -L root /dev/vg0/root
mkfs.ext4 -L var /dev/vg0/var

# Mount everything
mkdir -p /mnt/
mount /dev/disk/by-label/root /mnt
mkdir -p /mnt/var
mount /dev/disk/by-label/var /mnt/var

mkdir -p /mnt/boot
mount /dev/disk/by-label/boot /mnt/boot

swapon /dev/vg0/swap

# Install all the files
pacstrap /mnt base linux linux-firmware lvm2 mdadm intel-ucode vi wpa_supplicant

# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab
mdadm -D --scan >> /mnt/etc/mdadm.conf

# the following must be indented by tabs, not spaces
arch-chroot /mnt bash <<- EOD
	set -ex
	# Set time zone
	#ln -sf /usr/share/zoneinfo/Region/City /etc/localtime
	hwclock --systohc
	
	# Set localization
	sed -i 's/^#.*\(en_US.UTF-8\)/\1/' /etc/locale.gen
	locale-gen
	cat > /etc/locale.conf <<< LANG=en_US.UTF-8

	# the following must be indented by tabs, not spaces
	cat > /etc/hosts <<- EOF
		127.0.0.1	localhost
		::1	localhost
		#127.0.1.1 localhost.localdomain localhost
	EOF
	
	# Add initcpio support for storage
	cat > /etc/modprobe.d/raid0.conf <<< 'options raid0 default_layout=2'
	sed -i '/^HOOKS=/{ s/udev/systemd/; s/block/& mdadm_udev sd-lvm2/; }' /etc/mkinitcpio.conf
	sed -i '/^MODULES=/{ s/(/&dm-raid raid0/; }' /etc/mkinitcpio.conf
	mkinitcpio -P
	
	# Install boot loader
	bootctl install
	# the following must be indented by tabs, not spaces
	cat > /boot/loader/loader.conf <<- EOF
		default arch
		timeout	4
		console-mode	max
	EOF
	# the following must be indented by tabs, not spaces
	cat > /boot/loader/entries/arch.conf <<- EOF
		title	Arch Linux
		linux	/vmlinuz-linux
		initrd /intel-ucode.img
		initrd /initramfs-linux.img
		options root=LABEL=root rw
	EOF
	
EOD

reboot
